In [1]:
import json
import os
from torch.utils.data import Dataset
from pycocotools.coco import COCO

In [1]:
import torch

In [4]:
position_ids_l = torch.arange(5, dtype=torch.long, ).view(-1, 1)
position_ids_r = torch.arange(5, dtype=torch.long, ).view(1, -1)
print(position_ids_l)
print(position_ids_r)

distance = position_ids_l - position_ids_r
print(distance + 4)


tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[0, 1, 2, 3, 4]])
tensor([[4, 3, 2, 1, 0],
        [5, 4, 3, 2, 1],
        [6, 5, 4, 3, 2],
        [7, 6, 5, 4, 3],
        [8, 7, 6, 5, 4]])


In [9]:
with open("../data/annotations/coco_train.json", 'r') as file:
    ann = json.load(file)
    print(ann[9])
    # print(ann['annotations'][0])
    # print(ann['images'][0])
    # print(len(ann['images']))



{'caption': 'a young kid with head phones on using a computer ', 'image': 'val2014/COCO_val2014_000000318219.jpg', 'image_id': 'coco_318219'}


In [10]:
from PIL import Image
# image = Image.open('../data/val2014/COCO_val2014_000000252074.jpg').convert('RGB') 


True

In [13]:
annFile = '../data/annotations/captions_train2014.json'
coco = COCO(annFile)
img = coco.loadImgs(318556)
print(img)

loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
[{'license': 1, 'file_name': 'COCO_train2014_000000318556.jpg', 'coco_url': 'http://images.cocodataset.org/train2014/COCO_train2014_000000318556.jpg', 'height': 640, 'width': 480, 'date_captured': '2013-11-15 05:00:35', 'flickr_url': 'http://farm4.staticflickr.com/3133/3378902101_3c9fa16b84_z.jpg', 'id': 318556}]


In [3]:
from transformers import BertConfig
from transformers import ViTModel, ViTConfig
# 创建默认的BertConfig
config = ViTConfig()

# 打印配置参数
print(config)


ViTConfig {
  "attention_probs_dropout_prob": 0.0,
  "encoder_stride": 16,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.0,
  "hidden_size": 768,
  "image_size": 224,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "model_type": "vit",
  "num_attention_heads": 12,
  "num_channels": 3,
  "num_hidden_layers": 12,
  "patch_size": 16,
  "qkv_bias": true,
  "transformers_version": "4.31.0"
}



In [4]:
from transformers import T5Tokenizer

tkn = T5Tokenizer.from_pretrained("t5-small")
tkn('134')

You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565


{'input_ids': [3, 23747, 1], 'attention_mask': [1, 1, 1]}

In [1]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")


In [2]:
encoded = tokenizer("Hello, my dog is cute")
print(tokenizer.decode(encoded['input_ids']))
tokenizer.tokenize("Hello, my dog is cute")

[CLS] hello, my dog is cute [SEP]


['hello', ',', 'my', 'dog', 'is', 'cute']

In [5]:
tkn.tokenize("Hello, my dog is cute")

['▁Hello', ',', '▁my', '▁dog', '▁is', '▁cute']

In [1]:
from models.tokenizer import BertTokenizer
tkn = BertTokenizer.from_pretrained("bert-base-uncased")

/Users/ben-yeung/opt/anaconda3/envs/deep_learning/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
encoded_input = tkn( "Hello, my dog is cute", add_special_tokens=True)
print(tkn.decode(encoded_input['input_ids']))

[CLS] hello, my dog is cute [SEP]


In [40]:
sentences = ["Hello, my dog is cute", "I like to read books", "How are you?"]
tokenized_outputs = tokenizer(sentences, padding='longest', max_length=30)
print(tokenized_outputs)

{'input_ids': [[101, 7592, 1010, 2026, 3899, 2003, 10140], [101, 1045, 2066, 2000, 3191, 2808, 0], [101, 2129, 2024, 2017, 1029, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 0, 0]]}
